font_family family="Liga SFMonoNerdFont"
disable_ligatures never

hide_window_decorations yes
window_padding_width 4

cursor_shape block
cursor_blink_interval 1

linux_display_server wayland

include ./Rosé Pine.conf
