[ids]
*

[main]
# Quando o capslock é tocado e solto, envia 'esc'.
# Quando segurado, ativa a camada que chamamos de 'super_vim'.
capslock = overload(super_vim, esc)

# Define a camada 'super_vim' herdando o comportamento da tecla Meta/Super (M).
# Qualquer tecla apertada junto com Caps Lock que não esteja listada abaixo 
# vai se comportar como Super + Tecla.
[super_vim:M]

# Mapeia hjkl para as setas direcionais clássicas sem o modificador Super
h = left
j = down
k = up
l = right
