# Unbind the default prefix (Ctrl+b)
unbind C-b

# Set the new prefix to Ctrl+a
set-option -g prefix C-a

# Allow sending 'Ctrl+a' to applications (like bash or vim) by pressing it twice
bind-key C-a send-prefix

# Completely disable the status bar at the bottom
set -g status off
